name: Workflow Dispatch Test

on:
  push:
  workflow_dispatch:

jobs:
  check:
    uses: ./.github/workflows/test_call.yml
  deploy:
    needs: [check]
    name: deploy
    runs-on: ubuntu-20.04 # https://github.com/actions/runner-images/issues/6709#issuecomment-1361269639
    steps:
      # --------- use Python to install Python dependencies and run linter, tests, etc. ---------
      - uses: actions/checkout@v4
      - name: list files
        run: ls -la
