name: '[FrontEnd] Test on PR'

on:
  push:
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: list files
        run: ls -la
