name: '[FrontEnd] Test on PR'

on:
  push:
    branches-ignore:
      - 'main' # mainブランチを除外
      - 'develop' # develop ブランチを除外
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: error export
        run: exit 1
